name: my_tiny_map
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_speed_dial: ^6.2.0
  image_picker: ^0.8.7+5
  flutter_native_splash: ^2.3.1
  provider: ^6.0.5
  photo_manager: ^2.6.0
  geolocator: ^9.0.2
  kpostal: ^0.5.1
  kakao_map_plugin:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/

  fonts:
    - family: noto_sans
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
